### ISSUE TITLE
Update Terratests and Domain

### ISSUE THREAD

**Issue by charlesgreen** [simplycubed/terraform-google-static-assets#62]
simplycubed.tools domain is used for Terratests.

The domain has been transfered from GCP to Cloudflare and the GCP project was deleted.

1. Migrate this to a new GCP project.
2. Update Terraform SDK to use latest.
3. Update DNS to use Cloudflare.
4. Update Golang dependencies and ensure tests still function correctly

**Comment by hanzala1234** [comment]
working on this one now
